import { Router } from 'express';
import { authenticate, authorize } from '../middlewares/auth.middleware.js';
import { createOffer, decideOffer, providerCounter, listOffersByRequest, listAcceptedOffers } from '../controllers/ofertas.controller.js';
const router = Router();
router.post('/', authenticate, authorize('PROVEEDOR'), createOffer);
router.post('/:id/decision', authenticate, authorize('CLIENTE'), decideOffer);
router.post('/:id/counter', authenticate, authorize('PROVEEDOR'), providerCounter);
router.get('/request/:requestId', authenticate, listOffersByRequest);
router.get('/accepted', authenticate, listAcceptedOffers);
export default router;
