(async function init(){ try{ listarMisSolicitudes(); }catch(e){} })();
async function crearSolicitud(){ const name=document.getElementById('pr_name').value.trim(); const qty=Number(document.getElementById('pr_qty').value); const details=document.getElementById('pr_details').value.trim(); const msg=document.getElementById('pr_msg'); try{ const pr=await apiCrearSolicitud(name,qty,details); msg.textContent=`Solicitud creada: ${pr._id}`; msg.className='small success'; listarMisSolicitudes(); }catch(e){ msg.textContent=e.message; msg.className='small error'; } }
async function listarMisSolicitudes(){ const cont=document.getElementById('mis_solicitudes'); cont.innerHTML='Cargando...'; try{ const list=await apiMisSolicitudes(); cont.innerHTML=''; list.forEach(pr=>{ const div=document.createElement('div'); div.className='item'; div.innerHTML=`<div class="flex"><strong>${pr.productName}</strong> x ${pr.quantity}<span class="badge">${pr.status}</span></div><div class="small">${pr.details||''}</div><div class="actions"><input id="offer_${pr._id}" placeholder="ID oferta (si recibió)"/><input id="price_${pr._id}" placeholder="Precio (para contraoferta)" type="number"/><button onclick="aceptar(getOfferId('${pr._id}'))">Aceptar</button><button onclick="rechazar(getOfferId('${pr._id}'))">Rechazar</button><button onclick="contraofertar(getOfferId('${pr._id}'), getPrice('${pr._id}'))">Contraofertar</button></div>`; cont.appendChild(div); }); }catch(e){ cont.innerHTML=`<span class="error">${e.message}</span>`; } }
function getOfferId(id){ return document.getElementById('offer_'+id).value.trim(); }
function getPrice(id){ return document.getElementById('price_'+id).value.trim(); }
async function aceptar(offerId){ if(!offerId) return alert('Proporcione ID de oferta'); try{ await apiDecisionOferta(offerId,'ACCEPT'); alert('Oferta aceptada'); listarMisSolicitudes(); }catch(e){ alert(e.message); } }
async function rechazar(offerId){ if(!offerId) return alert('Proporcione ID de oferta'); try{ await apiDecisionOferta(offerId,'REJECT'); alert('Oferta rechazada'); listarMisSolicitudes(); }catch(e){ alert(e.message); } }
async function contraofertar(offerId, price){ if(!offerId) return alert('Proporcione ID de oferta'); if(!price) return alert('Proporcione precio'); try{ await apiDecisionOferta(offerId,'COUNTER', Number(price)); alert('Contraoferta enviada'); }catch(e){ alert(e.message); } }
async function cargarOfertas(){ const reqId=document.getElementById('of_req_id').value.trim(); const container=document.getElementById('ofertas_container'); if(!reqId) return alert('Proporcione ID de solicitud'); container.innerHTML='Cargando...'; try{ const offers=await apiListOffersByRequest(reqId); if(!offers.length){ container.innerHTML='<div class="small">No hay ofertas</div>'; return; } let html='<table><thead><tr><th>Proveedor</th><th>Precio Proveedor</th><th>Precio Oferta Cliente</th><th>Contraoferta Proveedor</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>'; offers.forEach(o=>{ html+=`<tr><td>${o.provider?o.provider.name:'—'}</td><td>${o.price}</td><td>${o.precioOfertaCliente??'-'}</td><td>${o.contraOfertaProveedor??'-'}</td><td>${o.status}</td><td><button onclick="aceptar('${o._id}')">Aceptar</button><button onclick="rechazar('${o._id}')">Rechazar</button><button onclick="promptContra('${o._id}')">Contraofertar</button></td></tr>`; }); html+='</tbody></table>'; container.innerHTML=html; }catch(e){ container.innerHTML=`<div class="error">${e.message}</div>`; } }
function promptContra(id){ const p=prompt('Precio de contraoferta (cliente):'); if(!p) return; contraofertar(id, Number(p)); }
